# Generated by Django 5.2.11 on 2026-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Your cover letter', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, DOCX)', null=True, upload_to='resumes/'),
        ),
    ]
